version: '3'
services:
  
  traefik:
    image: traefik:alpine
    labels:
      - traefik.frontend.rule=Host:traefik.example.com
      - traefik.port=8080
      - traefik.enable=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/traefik.toml:/etc/traefik/traefik.toml
      - ${PWD}/certs:/certs 
    ports:
      - 80:80
      - 443:443
      - 8080:8080 
  
  mifosx:
    build:
      context: ./mifos
      dockerfile: Dockerfile
    container_name: mifosx
    restart: always
    ports: 
      - 8443:8443
    labels:
      - traefik.frontend.rule=Host:loans.akilicapital.co.zw
      - traefik.port=8443
      - traefik.enable=true
  
     